# Generated by Django 4.2.23 on 2025-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TaskManager_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Category"},
        ),
        migrations.AlterModelOptions(
            name="subtask",
            options={"ordering": ["-created_at"], "verbose_name": "SubTask"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at"], "verbose_name": "Task"},
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_category_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="subtask",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_subtask_title"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_project_title"
            ),
        ),
        migrations.AlterModelTable(
            name="category",
            table="TaskManager_app_category",
        ),
        migrations.AlterModelTable(
            name="subtask",
            table="TaskManager_app_subtask",
        ),
        migrations.AlterModelTable(
            name="task",
            table="TaskManager_app_task",
        ),
    ]
